[General]
alt_bg=#383838
alt_item_css=
bg=#1c1c1c
css="
QScrollBar:vertical {
    width: 3px;
    background: ${alt_bg};
}

QScrollBar::handle:vertical {
    background: ${bg};
    border-radius: 1px;
}

QScrollBar::add-page:vertical,
QScrollBar::sub-page:vertical {
    background: ${alt_bg};
}

QScrollBar::add-line:vertical,
QScrollBar::sub-line:vertical {
    height: 0px;
}

QScrollBar:horizontal {
    height: 3px;
    background: ${alt_bg};
}

QScrollBar::handle:horizontal {
    background: ${bg};
    border-radius: 1px;
}

QScrollBar::add-page:horizontal,
QScrollBar::sub-page:horizontal {
    background: ${alt_bg};
}
"
css_template_items=items
css_template_main_window=main_window
css_template_menu=menu
css_template_notification=notification
cur_item_css="
    ;border: 0.1em solid ${sel_bg}"
edit_bg=#1a1a1a
edit_fg=#ffffff
edit_font="Segoe UI,11,-1,5,400,0,0,0,0,0,0,0,0,0,0,1,Regular"
fg=#dfdfdf
find_bg=#00689c
find_fg=#ffffff
find_font="Sans,10,-1,5,50,0,0,0,0,0"
font="Sans,10,-1,5,50,0,0,0,0,0"
font_antialiasing=true
hover_item_css=
icon_size=16
item_css=
item_spacing=
menu_bar_css="
    ;background: ${bg}
    ;color: ${fg}
    ;height: 0"
menu_bar_disabled_css="
    ;color: ${bg - #666}"
menu_bar_selected_css="
    ;background: ${sel_bg}
    ;color: ${sel_fg}"
menu_css="
    ;border: 1px solid ${sel_bg}
    ;background: ${bg}
    ;color: ${fg}"
notes_bg=#232323
notes_css=
notes_fg=#ffffff
notes_font="Sans,11,-1,5,50,0,0,0,0,0"
notification_bg=#333
notification_fg=#ddd
notification_font=
num_fg=#7f7f7f
num_font="Sans,7,-1,5,25,0,0,0,0,0"
num_margin=2
num_sel_fg=
search_bar="
    ;background: ${edit_bg}
    ;color: ${edit_fg}
    ;border: 1px solid ${alt_bg}
    ;margin: 2px"
search_bar_focused="
    ;border: 1px solid ${sel_bg}"
sel_bg=#61819c
sel_fg=#ffffff
sel_item_css=
show_number=false
show_scrollbars=false
style_main_window=true
tab_bar_css="
    ;background: ${bg - #222}"
tab_bar_item_counter="
    ;color: ${fg - #044 + #400}
    ;font-size: 6pt"
tab_bar_scroll_buttons_css="
    ;background: ${bg - #222}
    ;color: ${fg}
    ;border: 0"
tab_bar_sel_item_counter="
    ;color: ${sel_bg - #044 + #400}"
tab_bar_tab_selected_css="
    ;padding: 0.5em
    ;background: ${bg}
    ;border: 0.05em solid ${bg}
    ;color: ${fg}"
tab_bar_tab_unselected_css="
    ;border: 0.05em solid ${bg}
    ;padding: 0.5em
    ;background: ${bg - #222}
    ;color: ${fg - #333}"
tab_tree_css="
    ;color: ${fg}
    ;background-color: ${bg}"
tab_tree_item_counter="
    ;color: ${fg - #044 + #400}
    ;font-size: 6pt"
tab_tree_sel_item_counter="
    ;color: ${sel_fg - #044 + #400}"
tab_tree_sel_item_css="
    ;color: ${sel_fg}
    ;background-color: ${sel_bg}
    ;border-radius: 2px"
tool_bar_css="
    ;color: ${fg}
    ;background-color: ${bg}
    ;border: 0"
tool_button_css="
    ;color: ${fg}
    ;background: ${bg}
    ;border: 0
    ;border-radius: 2px"
tool_button_pressed_css="
    ;background: ${sel_bg}"
tool_button_selected_css="
    ;background: ${sel_bg - #222}
    ;color: ${sel_fg}
    ;border: 1px solid ${sel_bg}"
use_system_icons=false
