#!/usr/bin/env bash

sudo apt install libxkbfile-dev -y
git clone https://github.com/sergei-mironov/xkb-switch.git $HOME/personal/xkb-switch

cd $HOME/personal/xkb-switch
mkdir -p build && cd build
cmake ..
make
sudo make install
sudo ldconfig
